fix: Combobox not showing options upon input click
flipt-io/flipt pull request #2642
Opened 2024-01-11 00:49 UTC by julesglad

UI fix for issue #2545

2024-01-11 14:31 UTC, GeorgeMac commented
https://github.com/flipt-io/flipt/assets/1253326/cec591aa-588e-405f-83c2-7746e3dd6679

Hey @julesglad ! Thanks for taking this on.

I just gave it a build locally to try it out. The popover nicely populates for me now 🙌. However, I don't appear to be able to actually select any of the items now 🤔 I might try checkout and build main again to see if this problem is isolated to your change or not.

2024-01-12 02:40 UTC, julesglad commented
@GeorgeMac I was able to recreate on my end. Found a fix and pushed a commit, and it's ready to be tested. The commit automatically attached to this pull request since it was on the same branch, I should need no further action, correct?

2024-01-12 09:30 UTC, GeorgeMac requested changes
It works! Thanks @julesglad 🙏 There is one thing, just some debug statements need removing. Otherwise, I think it is good to go 🙌

2024-01-12 09:30 UTC, GeorgeMac commented on ui/src/components/forms/Combobox.tsx
> +
These can probably go now?
```suggestion
```

2024-01-12 15:20 UTC, julesglad commented
@GeorgeMac Oops, sorry about that. Removal pushed up now. 😳🫣🫣

2024-01-15 01:47 UTC, markphelps commented
looks and works great! thanks @julesglad !!

2024-01-15 01:47 UTC, merged