feat: add support for ghe and custom context path
flipt-io/flipt pull request #3127
Opened 2024-05-27 19:39 UTC by tvcsantos

This PR adds support for GHE (Self hosted GitHub Enterprise) and custom context path

Currently only github.com is supported. In some cases there is the need to have GitHub running on a self hosted instance due to security and isolation reasons. This PR adds support for all GitHub scenarios.

Also this PR adds support for custom context path. Redirection was broken on a deploy with a custom context path. It follows the standard using "X-Forwarded-Prefix" header to get the correct path context path for redirection.

Thanks for the project.

If you need me to update something feel free to comment ;)

2024-05-27 21:03 UTC, markphelps commented on .devcontainer/Dockerfile
> +COPY ./core ./core
thank you! 😄

2024-05-27 22:22 UTC, markphelps reviewed
thank you for the PR! will be a great feature to have and say that we now work with GHES!

Just a few minor suggestions.

I want to also loop in @GeorgeMac re the the redirect_address/forward prefix bits as he implemented the majority of the current auth flow

2024-05-27 22:22 UTC, markphelps commented on ui/src/components/header/UserProfile.tsx
> +        redirectAddress = redirectAddress?.trim();
if you run `mage ui:fmt` it will fix any ui formatting issues for you automatically

2024-05-27 22:22 UTC, markphelps commented on internal/server/authn/method/github/server.go
> +func getUserOrgs(apiURL string, ctx context.Context, token *oauth2.Token) (map[string]bool, error) {
```suggestion
func getUserOrgs(ctx context.Context, apiURL string, token *oauth2.Token) (map[string]bool, error) {
```

nit: its customary for `context.Context` to be the first argument

2024-05-27 22:22 UTC, markphelps commented on internal/server/authn/method/github/server.go
> +func getUserTeamsByOrg(apiURL string, ctx context.Context, token *oauth2.Token) (map[string]map[string]bool, error) {
```suggestion
func getUserTeamsByOrg(ctx context.Context, apiURL string, token *oauth2.Token) (map[string]map[string]bool, error) {
```
same as above

2024-05-27 22:24 UTC, markphelps commented
I added the `needs_docs` label just so we don't forget to update the [docs](https://github.com/flipt-io/docs) before creating a new release with this feature included

don't feel like you need to add the docs however, we can do that, unless of course you want to ;)

2024-05-28 10:34 UTC, GeorgeMac requested changes
I think this is awesome. Thank you for making this happen!

There is one tiny tidy up and one slight adjustment to building the x forwarded prefix I think might be worth doing.

On the redirect stuff, I had to refresh my memory a bit. I think the change here seems reasonable to me. However, I do think there is another way, involving leaning into that `X-Forwarded-Prefix` some more when setting the redirect location on the ForwardResponseOption.
Im trying to figure out what makes most for us going forward.

The alternative approach would be something like this:

We can get the original HTTP headers off the `ctx`, as GRPC gateway smuggles them in there. However, by default, it only copies across [permenant headers](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/runtime/context.go#L334) as defined in the IANA standard. So we would need to do a little bit of threading ourselves. It is possible to override the header matcher / extend it by wrapping this https://pkg.go.dev/github.com/grpc-ecosystem/grpc-gateway/runtime#DefaultHeaderMatcher to allow through other headers (`X-Forwarded-Prefix` in this case). Then we could get it in the `ForwardResponseOption` using the [`metadata.FromIncoming`](https://pkg.go.dev/google.golang.org/grpc/metadata#FromIncomingContext) function on the context and reading it off the metadata.
Long story short, is we could just redirect to the relative forwarded prefix in this situation and I think it would achieve the same ends? Correct me if I am wrong.

The only upside here is we don't need to encode the redirect address in the authentication metadata each time and have to thread that around. I don't know if anyone has any preferences on that here? (thoughts @markphelps @erka ?)

2024-05-28 11:46 UTC, tvcsantos commented on internal/server/authn/method/http.go
> +		forwardedPrefix := strings.Join(forwardedPrefixes, "")
Yes actually I was inspired by Spring :). Ty for the improvement 👍

2024-05-28 16:35 UTC, GeorgeMac requested changes
Hey @tvcsantos !

Just got off an offline sync with @markphelps where we touched base on this topic.
We're a little concerned about the context prefix more broadly.
There has been a previously opened issue and some work to attempt to address this:
- https://github.com/flipt-io/flipt/issues/2723
- https://github.com/flipt-io/flipt/pull/2734

The end result we have at the moment, I don't think solves the full story.
It probably works for situations where the UI is served using Vite, which is something we do in development only, not production. So you probably can get most of it working by changing the `base` for Vite, but this is not going to work in the production distributions of Flipt.

I might be mistaken here, maybe you could try building your application as an image and trying out your fix end to end with that instead of the dev environment?

```
mage dagger:run "build:flipt"
```
> This should produce an image you can run locally. The dagger output can be a bit obtuse, but you should see an image URL printed in there somewhere at the end.

But if this doesn't work because none of the paths are prefixed appropriately, I wonder if we should take what you have here and separate it into two pieces of work? One for context path and one for GHE. Then we can get your GHE changes in ASAP and think through the broader context paths issue as its own change. WDYT?

2024-05-28 22:22 UTC, tvcsantos commented
> I added the `needs_docs` label just so we don't forget to update the [docs](https://github.com/flipt-io/docs) before creating a new release with this feature included
> 
> don't feel like you need to add the docs however, we can do that, unless of course you want to ;)

I will do the docs if needed no worries there

2024-05-28 22:25 UTC, tvcsantos commented
@GeorgeMac I will try to give you feedback on it still this week. But yeah I agree with you maybe we should split in 2 PRs.

I will try to have time tomorrow to split them and then provide feedback regarding the custom path topic.

Thanks for the comments and the collaboration

2024-05-29 08:37 UTC, GeorgeMac commented
Thank you for your contributions @tvcsantos 🙌 We definitely want to get these changes in either way :D

2024-05-29 15:26 UTC, erka commented
Thank you for your hard work here @tvcsantos. 

@GeorgeMac I've made some updates regarding the custom context path in #3135, specifically involving the X-Forwarded-Prefix header. These changes are intended to help advance this PR, but they might be somewhat bold. I would appreciate your feedback on this.

2024-05-30 09:37 UTC, tvcsantos commented
@markphelps @GeorgeMac created a separate PR to deal with the addition of GHE support #3136.

2024-05-30 09:42 UTC, tvcsantos commented
Since this thread on the PR is mostly about the context path feature. I will cleanup this PR having only the context path related code, change the title and maintain it open.

2024-05-30 11:26 UTC, tvcsantos commented
Regarding the context path fix, actually in order to test before opening the PR I have created a docker image on my GitHub

https://github.com/tvcsantos/flipt/tree/feature/add-self-hosted-v2

```
docker pull ghcr.io/tvcsantos/flipt:feature-add-self-hosted-v2
```

2024-06-07 10:17 UTC, tvcsantos commented
I will close this PR since this is being addressed on other #3135

2024-06-07 10:17 UTC, closed without merging