FLI-1258: pass org and teams to metadata
flipt-io/flipt pull request #3654
Opened 2024-11-25 15:45 UTC by devumesh

**Approach:**
1. Get orgs and teams of the authenticated user by default. I went with this approach because there might be a case where authentication is not needed based on the orgs or teams but authorization might be needed to control RBAC.
2. Validate authentication on orgs `if orgs > 0`.
3. Validate team `if allowed_teams > 0`.
4. Convert orgs to list (stringified) and store in `io.flipt.auth.github.orgs`.
5. Convert teams to map `{org1: [list of teams],org2: [list of teams]}` and store in `io.flipt.auth.github.teams`.

2024-11-25 18:40 UTC, erka requested changes
Thank you for the contribution @devumesh!

There are few things which we should address in this PR.

Original code hides some aspects of  Github login integration and tests does not cover it.  There should be a token with `read:org` in scope to fetch user's orgs and teams. Originally the check happens on the configuration level https://github.com/flipt-io/flipt/blob/main/internal/config/authentication.go#L600-L602.  Without that  `getUserOrgs` and `getUserTeamsByOrg` api requests will fail and auth flow will be broken for those who don't have that scope in their Flipt configuration. 

Also I would like to discuss another thing. I think we should not store all user's orgs and teams, if there is a configuration requirement for specific organizations and/or teams for privacy reasons. wdyt? cc: @markphelps

2024-11-26 14:47 UTC, markphelps requested changes
thanks @devumesh ! I agree with @erka that we could use a bit more testing.

@erka im not too concerned about storing all the orgs/team memberships in the metadata tbh. how are you thinking we would limit what is stored in metadata? another configuration option?

2024-11-26 14:47 UTC, markphelps commented on internal/server/authn/method/github/server.go
> +	storageMetadataGitHubOrgs              = "io.flipt.auth.github.orgs"
```suggestion
	storageMetadataGitHubOrgs              = "io.flipt.auth.github.organizations"
```

2024-11-26 14:47 UTC, markphelps commented on internal/server/authn/method/github/server.go
> +	userOrgs, err := getUserOrgs(ctx, token, apiURL)
note for another PR: we should consider caching these results in memory for a period of time as now we're doing these REST calls on every request if an org is using GitHub authn and the orgs/team membership do not change nearly that often

2024-11-26 21:15 UTC, erka commented
> @erka im not too concerned about storing all the orgs/team memberships in the metadata tbh. how are you thinking we would limit what is stored in metadata? another configuration option?

Let say, that Flipt configuration has `allowed_organizations` which set to `[a, b]`. And user has orgs `[a, d, f, g, e, t]`. Is there any usecase when those `d, f, g, e, t` could be useful? I think that only allowed_organizations should be added to metadata in this case.

2024-11-27 00:00 UTC, markphelps commented
> > @erka im not too concerned about storing all the orgs/team memberships in the metadata tbh. how are you thinking we would limit what is stored in metadata? another configuration option?
> 
> 
> 
> Let say, that Flipt configuration has `allowed_organizations` which set to `[a, b]`. And user has orgs `[a, d, f, g, e, t]`. Is there any usecase when those `d, f, g, e, t` could be useful? I think that only allowed_organizations should be added to metadata in this case.

Ah that's a good point. I was thinking you were suggesting another config property but I agree with you we should only track the ones configured.

2024-11-27 14:38 UTC, devumesh commented
> Let say, that Flipt configuration has `allowed_organizations` which set to `[a, b]`. And user has orgs `[a, d, f, g, e, t]`. Is there any usecase when those `d, f, g, e, t` could be useful? I think that only allowed_organizations should be added to metadata in this case.

I have a doubt. If the user doesn't configure `allowed_organizations`, should we need to pass `[a, d, f, g, e, t]` orgs for authz or authn is needed for authz with github?

2024-11-27 15:08 UTC, erka commented
> Hi @erka, correct me If I'm understanding wrong. `read:org` in scope should me mandated when using Github?

Maybe if your Flipt instance is in internet. But I don't think we can't change it, at least in v1.

It started with `user:email` scope. One day someone asked for organization filter because of access control concern. I believe they had the Flipt instance in public network. Later someone else asked for teams support.  For these orgs and team filters `read:org` is needed.  The [documentation](https://docs.flipt.io/configuration/authentication#github)  looks like a history in some sense. 

It would be great to not break auth flow for those first adopters of login with Github.

2024-11-27 15:12 UTC, erka commented
> I have a doubt. If the user doesn't configure `allowed_organizations`, should we need to pass `[a, d, f, g, e, t]` orgs for authz or authn is needed for authz with github?

Yeah, it's tricky... If there is `read:org` in configuration scopes , let's read them and add to metadata, if not - we can't fetch them and they should be empty.  wdyt?

2024-11-28 04:29 UTC, devumesh commented
> Yeah, it's tricky... If there is `read:org` in configuration scopes , let's read them and add to metadata, if not - we can't fetch them and they should be empty. wdyt?

Yeah I guess it should work. If the allowed org is not provided are you suggesting to send all the retrieved orgs for authz?
or
Authz for github with org and teams valid only with allowed orgs for authn?

Can you please clarify this.

2024-11-28 08:35 UTC, devumesh commented on internal/server/authn/method/github/server.go
> +	storageMetadataGitHubOrgs              = "io.flipt.auth.github.orgs"
Hi @markphelps , fixed this

2024-11-28 11:47 UTC, erka commented
@devumesh Let me explain my vision with examples so you could validate them.

#### 1. no read:org in scopes 
No way to get user's organizations and teams, so metadata for organizations and teams should be empty

#### 2. read:org in scopes

##### 2.1. no organizations restrictions
Fetch user's orgs and teams and add them all to metadata. For example, user has `a, b, e` orgs, so metadata will have `a, b, e` too. 

##### 2.2. with organization restrictions
Fetch user's orgs and teams, filter them and include only required organizations which user has. As example, user has `a, b, c, d` organizations and restriction contains `a, b, e`. Only `a, b` orgs and teams of `a, b` should be included in metadata.

##### 2.3. with organization and team restrictions
Same as 2.2 but filter user's teams as well. 

WDYT?

2024-11-28 12:12 UTC, devumesh commented
> Fetch user's orgs and teams, filter them and include only required organizations which user has. As example, user has `a, b, c, d` organizations and restriction contains `a, b, e`. Only `a, b` orgs and teams of `a, b` should be included in metadata.

Hey @erka , thanks. I have made changes as you mentioned. But I have made a mistake where instead of passing orgs `a, b` I'm passing `a, b, e` (passing all the orgs mentioned in the org restriction). Same mistake I made for teams also. I will fix that.

2024-11-29 19:15 UTC, markphelps commented
@all-contributors please add @devumesh for code

2024-11-29 22:20 UTC, markphelps approved these changes
Thank you!

2024-11-30 02:00 UTC, devumesh commented
Hi @markphelps, thank you. committed your suggestion. Please review.

2024-11-30 15:49 UTC, merged